### ISSUE TITLE
Service Bus output bindings 

### ISSUE THREAD

**Issue by DibranMulder** [Particular/NServiceBus.AzureFunctions.ServiceBus#110]
For now its **not** possible to use Azure Functions ServiceBusTriggers and OutputBindings interchangeably. The `FunctionsEndpoint` doesn't support any `Send` or `Publish` functionality and therefore only handling messages is supported and sending messages is not supported.

This is not clear in the documentation nor in the examples. The following blog https://particular.net/blog/support-for-azure-functions contains the following example:
```csharp
[FunctionName("MyFunction")]
[return: ServiceBus("nextreceiverqueue")]
public static async Task Run(
    [ServiceBusTrigger(queueName: "receiverqueue")]
    MyRequestClass message,
    [ServiceBus("topic", Connection = "ConnectionString", EntityType = EntityType.Topic)]IAsyncCollector<SomethingHappenedEvent> collector,
    ILogger logger)
{
    logger.LogInformation("Hey, a message with id {0} arrived!", message.Id);

    await collector.AddAsync(new SomethingHappenedEvent { Id = message.Id });

    return new MyNextRequestClass { Id = message.Id };
}
```

Note the `await collector.AddAsync(new SomethingHappenedEvent { Id = message.Id });` line. This posts a message on the servicebus without any headers or other metadata. Such messages can not be processsed by the message handlers of NServiceBus since the message itself can't be converted to the appropriate type. 

Secondly, the [documentation ](https://docs.particular.net/samples/previews/azure-functions/service-bus/) uses the Azure CLI to create a ServiceBus queue. This is not good since the NServiceBus systems expects a topic with filters and so on to route the messages to the appropriate queues. If this is not setup well then creating a Send-Only endpoint isn't going to be helpful. One should rather use the dotnet tool or nservicebus cli to create the `endpoint`, `subscriptions` and `queues`. 

It would be really great if the `FunctionsEndpoint` could somehow expose a wrapper around the `IAsyncCollector` and use the NServiceBus method to send messages. If this is not workable then maybe the extension should have a custom OutputBinding for NServiceBus messages. 

Hope this is any helpful.

**Comment by SeanFeldman** [comment]
Hi @DibranMulder,

Thank you for the feedback. There are a few items in your issue description that feel like separate issues and I'd like to focus on each one separately to see if there's anything that can be done or is already available.

> The FunctionsEndpoint doesn't support any Send or Publish

Have you had a chance to review the [documentation](https://docs.particular.net/previews/azure-functions-service-bus) and the [sample](https://docs.particular.net/samples/previews/azure-functions/service-bus/)? NServiceBus.Functions is fully capable of sending/publishing messages and I wonder if you refer to a different scenario. 

> The following blog particular.net/blog/support-for-azure-functions contains the following example:

The referenced Functions code you've referenced is from the blog post, Simple message dispatching section, used to demonstrate the challenges with using raw Functions. You'll notice that the very next code block (below) was the equivalent using NServiceBus.

```c#
async Task Handle(MyRequestClass message, IMessageHandlerContext context)
{
    Log.LogInformation("Hey, a message with id {0} arrived!", message.Id);

    await context.Publish(new SomethingHappenedEvent { Id = message.Id });
    await context.Send(new MyNextRequestClass { Id = message.Id });
}
```

It's important to note that the raw Function becomes nothing but pass through to the `await endpoint.Process(message, executionContext, logger);` (2nd code snippet in the post), where `endpoint` is a `FunctionEndpoint`.

> It would be really great if the FunctionsEndpoint could somehow expose a wrapper around the IAsyncCollector and use the NServiceBus method to send messages. If this is not workable then maybe the extension should have a custom OutputBinding for NServiceBus messages.

In a way it is. I highly recommend downloading the [sample](https://docs.particular.net/samples/previews/azure-functions/service-bus/) which demonstrates what I suspect exactly what you're looking for.

In regards to the 2nd item, 

> Secondly, the documentation uses the Azure CLI to create a ServiceBus queue. This is not good since the NServiceBus systems expects a topic with filters and so on to route the messages to the appropriate queues. If this is not setup well then creating a Send-Only endpoint isn't going to be helpful. One should rather use the dotnet tool or nservicebus cli to create the endpoint, subscriptions and queues.

There's already a [dedicated issue](https://github.com/Particular/NServiceBus.AzureFunctions.ServiceBus/issues/94) to investigate wherever the experience can be improved. Perhaps adding a comment or upvoting it would help to indicate interest in the topic (no pun intended).

**Comment by SeanFeldman** [comment]
@DibranMulder, I'm assuming you got the answers to your questions and all set. Will close the issue. If you feel that not all of your questions were fully answered, please post a follow-up comment. Thank you.

**Comment by andrekiba** [comment]
@SeanFeldman I comment on this just to know if I understood correctly (reading the post...maybe @DibranMulder wanted to ask something like this, I don't know :-)).
When we are inside an handler we can do what we want (send, publish...) but, being inside an handler means that we are reacting to something (someone else sent the message).
Sometimes your function is the "entry point", triggered someway. Starting from this function you want to "send the first message". In this case you don't have any handler but you want to speak with the nservicebus ecosystem.
In this case is the [native integration](https://docs.particular.net/samples/azure/native-integration-asb/) the correct way to proceed for both cases, send and publish?
Practically, does it mean that to start a conversation you only have to put a message on azure service bus, you don't have to startup any nservicebus endpoint? Thank you!

**Comment by SeanFeldman** [comment]
> Practically, does it mean that to start a conversation you only have to put a message on azure service bus, you don't have to startup any nservicebus endpoint? Thank you!

Yes and no @andrekiba. Yes, you'd need a message, but you don't have to put it in a queue. You could have an HTTP or Timer triggered functions that spoofs a message and invokes FunctionEndpoint.Process(). It's a bit of a hack until a proper implementation is in place. The request to use NServiceBus outside of a handler context is already tracked in #82. I would encourage you to add a comment with your requirements to that issue.

**Comment by andrekiba** [comment]
Thank you @SeanFeldman, so this

>  You could have an HTTP or Timer triggered functions that spoofs a message and invokes FunctionEndpoint.Process()

for me it is not clear but I'll put the comment in #82 :-)
