### ISSUE TITLE
No option to mock FunctionEndpoint 

### ISSUE THREAD

**Issue by Claker** [Particular/NServiceBus.AzureFunctions.ServiceBus#113]
Hi, I am trying to unit test my azure function which uses a FunctionEndpoint.
I did not find any option to mock it so I can pass it to the ctor of my new function instance.

This github repo does not have the option to request a feature so I created it as an issue.
Can you please advice?

        private readonly FunctionEndpoint _endpoint;

        public Function(FunctionEndpoint endpoint)
        {
            _endpoint = endpoint;
        }

        [FunctionName(NServiceBusConstants.CreateUserEndpoint)]
        public async Task Run([ServiceBusTrigger(NServiceBusConstants.CreateUserEndpoint)]
            Message message, ILogger logger, ExecutionContext executionContext)
        {
            await _endpoint.Process(message, executionContext, logger);
        }

**Comment by danielmarbach** [comment]
@Claker I have transferred the issue into the corresponding repository. I guess a change like

https://github.com/Particular/NServiceBus.AzureFunctions.ServiceBus/pull/114

would enable the scenarios you described right?

**Comment by Claker** [comment]
Morning @danielmarbach,

Yes! Awesome! 😄 
Thanks for taking the feedback on board and adding a fix !

**Comment by Claker** [comment]
Hi @danielmarbach, do you think the PR will be merged and released early next year?
BTW, have a great Holiday!

**Comment by SeanFeldman** [comment]
@Claker, yes. The plan is to address it after the holidays, early 2021.

**Comment by danielmarbach** [comment]
@Claker I have released it as part of 0.4.0 and updated the documentation. The official release announcement will soon be posted to the discuss group. Thanks for your patience while I was eating way too many Christmas cookies.

**Comment by danielmarbach** [comment]
Here is the announcement link

https://discuss.particular.net/t/nservicebus-azurefunctions-azureservicebus-0-4-0-minor-release-available/2235

**Comment by Claker** [comment]
Thank you very much!!
The company I work at (Serko Ltd.) are currently preparing to buy the licenses we need to use NServiceBus in Prod and we might use it a lot more in the future. 
We are still experimenting with it in Dev and this is the first time we try it.

If we have more questions, what would be a good channel to ask? Would github be ok or your website or is there another recommended way?

**Comment by danielmarbach** [comment]
@Claker All our available support channels can be found on https://particular.net/support

If you have a question, concern regarding a concrete library/product you can also open issues in the corresponding repository. For general questions I recommend the [discuss group](https://discuss.particular.net/). If sharing of internal things is required it can always be transitioned into a support case by requesting a non-critical support.
