### ISSUE TITLE
Azure Functions Preview on .NET 5

### ISSUE THREAD

**Issue by johnkors** [Particular/NServiceBus.AzureFunctions.ServiceBus#131]
Hi,

Any thoughts on how to get an endpoint working with the new Azure Functions SDK (for .NET 5 support)?

See https://github.com/Azure/azure-functions-dotnet-worker-preview

**Comment by SeanFeldman** [comment]
Thank you @johnkors for raising the question.

Azure Functions out-of-process worker is not GA-ed and is not possible to run in production. Isn't that the case? It also doesn't even support all the [standard triggers](https://github.com/Azure/azure-functions-dotnet-worker-preview/issues/14) currently as [stated in `README.MD`](https://github.com/Azure/azure-functions-dotnet-worker-preview#functions). Note that Particular Previews are [supported in production](https://docs.particular.net/previews/support-policy) and customers expect to be able to use those in their production workloads. Once the out-of-process Functions worker will be stable to be used in production,  we'll be looking at what's needed for it.

What's your current use case and how would you use it given the information above? Thank you.

**Comment by johnkors** [comment]
My use case is I'm working in a .NET 5 code base, so ideally the function would also be running 5 instead of 3.1. 

I by chance used C# records instead of classes to define my message contracts, which are not supported in 3.1. Not big issue to convert to classes and use 3.1 functions, just wanted to investigate if it was feasible to run on the preview first.

FWIW, I got a Function sample up with ServiceBusBinding on 5 that triggers fine, but currently lack a way of getting hold of MessageId/Headers to pass to the NServiceBus bridge (IFunctionEndpoint.Process). 

Not critical, just wondered if you had looked at the previews and had some pointers. Totally understandable if you want to wait for GA.

**Comment by johnkors** [comment]
Btw, for anyone other than me interested, my current hacks are:

```csharp
.ConfigureFunctionsWorker((_, b) =>
{
    b.Services.AddSingleton<IFunctionEndpoint,FunctionEndpoint>(
        a => new FunctionEndpoint(b => new ServiceBusTriggeredEndpointConfiguration("My.Functions", "ASB_CONNECTIONSTRING")));
    b.UseFunctionExecutionMiddleware();
})
```

```csharp
// from microsoft.azure.functions.worker/1.0.0-preview3
using FunctionExecutionContext = Microsoft.Azure.Functions.Worker.Pipeline.FunctionExecutionContext;

[FunctionName("PreviewTest")]
public Task Run(
  [ServiceBusTrigger("My.Functions", Connection = "ASB_CONNECTIONSTRING")] string body, 
  FunctionExecutionContext context)
{    
    var endpoint = context.InstanceServices.GetService<IFunctionEndpoint>();    
    endpoint.Process(..);
}
```

Unfortunately it only works to define the `ServiceBusTrigger` parameter as a `string`, which only provides the body of the message. There is some ongoing effort to investigate it at least ([issues/106](https://github.com/Azure/azure-functions-dotnet-worker/issues/106) , [issues/39](https://github.com/Azure/azure-functions-dotnet-worker-preview/issues/39) ). Haven't found a way to get hold of MessageId & Headers yet..

**Comment by SeanFeldman** [comment]
Given how in-flex the support for out-of-process Functions is the ideal situation would be to let the dust settle on the Functions side and then look into adopting it for NServiceBus. Functions API can and will change,  causing continuous catch-up. I also haven't seen a solid answer about supporting .NET 5 in production. Rather, an answer that this work is done to ensure .NET 6 is a smooth sail.

On the NServiceBus side, you have a guarantee that when Functions API changes are solid, the support for those will be added.
Thank you for asking and don't hesitate to raise any other questions/suggestions.

**Comment by SeanFeldman** [comment]
The issue to support the upcoming isolated worker will be tracked in https://github.com/Particular/NServiceBus.AzureFunctions.ServiceBus/issues/148

**Comment by SeanFeldman** [comment]
@johnkors, are you still looking for Isolated Worker SDK support? If you do, please indicate on #148. Thank you.

**Comment by johnkors** [comment]
Will do, thanks!
