### ISSUE TITLE
ETA for production use

### ISSUE THREAD

**Issue by simongullberg** [Particular/NServiceBus.AzureFunctions.ServiceBus#40]
We rely heavily on NServiceBus in our services and we just started to develop a lot of services as Azure Functions which we think is great. Unfortunately the lack of support for Azure Functions in NServiceBus excludes us from using Azure Service Bus triggered functions in our environment.

It would be much appreciated with an ETA for the support of Azure Functions in production use.

**Comment by Ozzmosiz** [comment]
Any update on this?

**Comment by a09sebes** [comment]
Also curious on the state of this.

**Comment by olofalmqvist** [comment]
I would also like to know if there has been any progress on this issue.

**Comment by CarljohanDanling** [comment]
This feature sounds nice, are you planning on implementing this?

**Comment by SeanFeldman** [comment]
@simongullberg, @Ozzmosiz , @a09sebes, @olofalmqvist, @CarljohanDanling,

Thank you for your interest in NServiceBus support for Azure Functions.
The good news is that we're moving forward with Azure Functions support and will be delivering something in the near future (no ETAs or dates at this point). The upcoming release will allow you to use it in production with **full support**.

If you're interested in receiving more information, please send your information to [our support](https://particular.net/support). I'll add this thread to the list of interested customers. An update will be posted here to let others, who have subscribed to the issue, know when there's an update.

**Comment by SeanFeldman** [comment]
Support for Azure Functions has been released as a [Public Preview](https://docs.particular.net/previews/) and is production-ready, backed by [support policy](https://docs.particular.net/previews/support-policy).  Currently, supported triggers include
- Azure Service Bus ([announcement](https://discuss.particular.net/t/nservicebus-azurefunctions-servicebus-public-preview-release-available/1910))
- Azure Storage Queues ([announcement](https://discuss.particular.net/t/nservicebus-azurefunctions-servicebus-public-preview-release-available/1910))

The packages are fully supported for use in production.
