### ISSUE TITLE
NServiceBus does not collaborate properly with ServiceCollection provided by Azure Functions 

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.AzureFunctions.ServiceBus#92]
## Describe the problem

When trying to use NServiceBus for Azure Functions and register Entity Framework (EF) into the container, get the following exception:

```
Unable to resolve service for type 'Microsoft.Azure.WebJobs.Script.IEnvironment' while attempting to activate 
  'Microsoft.Azure.WebJobs.Script.Configuration.ScriptHostOptionsSetup'.
```

After raising the https://github.com/Azure/azure-functions-host/issues/6783 issue with Azure Functions it became apparent that the way NServiceBus.AzureFunctions is leveraging the ServiceCollection is wrong for both the static and non-static usages.

When instantiating an NServiceBus.AzureFunctions `FunctionEndpoint` using the static approach, the `ServiceCollection` does not share any services/components with Azure Functions SDK. When instantiating an NServiceBus.AzureFunctions `FunctionEndpoint` using the non-static approach using DI, the `ServiceCollection` that we get in the Startup class to configure services is a subset of all the services. Regardless of the approach, **the service provider built by NServiceBus will not contain all the dependencies**.

## Potential workaround

Not possible with the current implementation.

## Potential solutions

The NServiceBus.AzureFunctions implementation needs to treat the Azure Functions hosted endpoint as an endpoint with an [externally-managed container](https://docs.particular.net/nservicebus/dependency-injection/extensions-dependencyinjection#externally-managed-mode), using the service collection and service provider supplied by Azure Functions. This means using the DI style of Functions and not the static implementation, providing an extension method such as `.UseNServiceBus(...)`. This extension method would be used to configure the `FunctionEndpoint`.

## Additional information to help with this issue

I've created a [repository](https://github.com/SeanFeldman/NSB-Function-DI-repro) with all of the findings
- [Statically configured NServiceBus endpoint](https://github.com/SeanFeldman/NSB-Function-DI-repro/tree/master/AzureFunctions.ASBTrigger.Static)
- [NServiceBus endpoint configured using DI](https://github.com/SeanFeldman/NSB-Function-DI-repro/tree/master/AzureFunctions.ASBTrigger.DI) (Startup class approach)
- [Working native Azure Function using DI](AzureFunctions.NativeTrigger)
- [Attempt to reproduce the issue w/o using NServiceBus but emulating what it does](https://github.com/SeanFeldman/NSB-Function-DI-repro/tree/master/AzureFunctions.ServiceCollectionWrapper)
  - [A fix to the issue introduced with NServiceBus creating its own service provider](https://github.com/SeanFeldman/NSB-Function-DI-repro/blob/d0210edbf819e088b9fdb54e3c6f218e72ee1646/AzureFunctions.ServiceCollectionWrapper/AzureServiceBusNativeTriggeredFunctionWithWrapper.cs#L28)
- [A console application to generate a kick-off message](https://github.com/SeanFeldman/NSB-Function-DI-repro/tree/master/AzureFunctions.Console)

## Summary

This issue prevents the adoption of NServiceBus.AzureFunctions when 3rd party dependencies fail to be resolved.

**Comment by andrekiba** [comment]
Hope to try this soon! 😉

**Comment by SeanFeldman** [comment]
The work on this issue has started.

**Comment by SeanFeldman** [comment]
Closed via https://github.com/Particular/NServiceBus.AzureFunctions.ServiceBus/commit/2c3f601918fffef267130dedd8bad5e81ba2546a

**Comment by SeanFeldman** [comment]
0.3.0 has been released. See the [announcement](https://discuss.particular.net/t/nservicebus-azurefunctions-azureservicebus-0-3-0-minor-release-available/2180).
